name: Test_Deploy to AWS Lambda

on:
  push:
    branches: ["dev"]
    paths:
      - "Lambda_deploy_Test/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23" # Goのバージョン

      - name: Build Lambda binary # Lambda用にLinux用バイナリを生成
        run: |
          cd Lambda_deploy_Test
          GOOS=linux GOARCH=amd64 go build -o main main.go

      - name: Zip Lambda binary # ZIPファイルを作成
        run: |
          cd Lambda_deploy_Test
          zip function.zip main

      - name: Deploy to AWS Lambda # AWS Lambdaへデプロイ
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1 # 東京リージョン
          function-name: TestLambdaFunction # 実際のLambda関数名に置き換え
          zip-file: Lambda_deploy_Test/function.zip
