name: Test_Deploy to AWS Lambda

on:
  push:
    branches: ["dev"]
    paths:
      - "Lambda_deploy_Test/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    # OIDCを利用するためにはid-tokenパーミッションが必要
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23" # Goのバージョン

      - name: Build and zip # ビルド & ZIP作成
        run: |
          cd Lambda_deploy_Test
          GOOS=linux GOARCH=amd64 go build -o bootstrap main.go
          zip function.zip bootstrap

      - name: Deploy to AWS Lambda # AWS Lambdaへデプロイ
        uses: appleboy/lambda-action@v0.1.7
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1 # 東京リージョン
          function-name: TestLambdaFunction # 実際のLambda関数名に置き換え
          zip-file: Lambda_deploy_Test/function.zip
